default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: realbid_dev
  username: <%= ENV["PG_USERNAME"] || "postgres" %>
  password: <%= ENV["PG_PASSWORD"] || "password" %>
  host: <%= ENV["PG_HOST"] || "localhost" %>
  port: <%= ENV["PG_PORT"] || 5432 %>

test:
  <<: *default
  database: realbid_test
  username: <%= ENV["PG_USERNAME"] || "postgres" %>
  password: <%= ENV["PG_PASSWORD"] || "password" %>
  host: <%= ENV["PG_HOST"] || "localhost" %>
  port: <%= ENV["PG_PORT"] || 5432 %>

production:
  <<: *default
  url: <%=ENV["DATABASE_URL"] %>?sslmode=require

cable:
  <<: *default
  url: <%=ENV["DATABASE_URL"] %>?sslmode=require


queue:
  <<: *default
  url: <%=ENV["DATABASE_URL"] %>?sslmode=require

cache:
  <<: *default
  url: <%=ENV["DATABASE_URL"] %>?sslmode=require
