default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["PG_HOST"] || "localhost" %>
  port: <%= ENV["PG_PORT"] || 5432 %>
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: realbid_dev
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: <%= ENV["PG_HOST"] %>
  port: <%= ENV["PG_PORT"] || 5432 %>

test:
  <<: *default
  database: realbid_test
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  host: <%= ENV["PG_HOST"] %>
  port: <%= ENV["PG_PORT"] || 5432 %>

production:
  url: <%= Rails.application.credentials.database_url %>

cable:
  url: <%= Rails.application.credentials.database_url %>

queue:
  url: <%= Rails.application.credentials.database_url %>


